sudo: required
services:
  - docker

# Build images to be tested
before_install:
  - docker build -t soundestmammal/c19insights-client-test -f ./client/Dockerfile.dev ./client

# Run tests here
script:
  - docker run -e CI=true soundestmammal/c19insights-client-test npm test

after_success:
  - docker build -t soundestmammal/c19insights-client ./client
  - docker build -t soundestmammal/c19insights-server ./server
  - docker build -t soundestmammal/c19insights-nginx ./nginx
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push soundestmammal/c19insights-client
  - docker push soundestmammal/c19insights-server
  - docker push soundestmammal/c19insights-nginx

deploy:
  provider: elasticbeanstalk
  region: us-east-2
  app: c19insights
  env: C19insights-env
  bucket_name: elasticbeanstalk-us-east-2-670541471230
  bucket_path: docker-c19insights
  on:
    branch: containerize
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
